REM Linux, macOS, or Unix

REM $ export AWS_ACCESS_KEY_ID=
REM $ export AWS_SECRET_ACCESS_KEY=
REM $ export AWS_DEFAULT_REGION=us-west-2


REM Windows
set AWS_ACCESS_KEY_ID=
set AWS_SECRET_ACCESS_KEY=